export default Object.freeze({
  // navigators
  HOME_TAB_NAVIGATOR: 'HOME_TAB_NAVIGATOR',
  AUTH_SCREEN: 'AUTH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  FORGOT_PASSWORD_BY_EMAIL_SCREEN: 'FORGOT_PASSWORD_BY_EMAIL_SCREEN',
  FORGOT_PASSWORD_BY_SMS_SCREEN: 'FORGOT_PASSWORD_BY_SMS_SCREEN',
  SET_PASSWORD_SCREEN: 'SET_PASSWORD_SCREEN',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',

  //Home Tabs
  HOME_TAB_SCREEN: 'HOME_TAB_SCREEN',
  FAVOURITE_TAB_SCREEN: 'FAVOURITE_TAB_SCREEN',
  NEARBY_TAB_SCREEN: 'NEARBY_TAB_SCREEN',
  CART_TAB_SCREEN: 'CART_TAB_SCREEN',
  ACCOUNT_TAB_SCREEN: 'ACCOUNT_TAB_SCREEN',
});

export type RootStackParamList = {
  HOME_TAB_NAVIGATOR: any;
  AUTH_SCREEN: any;
  LOGIN_SCREEN: any;
  SIGNUP_SCREEN: any;
  SPLASH_SCREEN: any;
  FORGOT_PASSWORD_SCREEN: any;
  FORGOT_PASSWORD_BY_EMAIL_SCREEN: any;
  FORGOT_PASSWORD_BY_SMS_SCREEN: any;
  SET_PASSWORD_SCREEN: any;
  ONBOARDING_SCREEN: any;
  HOME_TAB_SCREEN: any;
  FAVOURITE_TAB_SCREEN: any;
  NEARBY_TAB_SCREEN: any;
  CART_TAB_SCREEN: any;
  ACCOUNT_TAB_SCREEN: any;
};
