import {StyleSheet} from 'react-native';
import {colors} from '../../../../theme/colors';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';

export const styles = StyleSheet.create({
  main: {
    marginBottom: 10,
  },
  wrapper: {
    backgroundColor: 'white',
  },
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  title: {
    backgroundColor: '#FF9200',
    color: 'white',
    fontSize:moderateScale(12),
    borderRadius: 20,
    padding: 3,
    width: 100,
    textAlign: 'center',
    marginTop: 10,
    marginStart: 20,
  },
  itemWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    margin: 10,
    width: '65%',
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    marginStart: 30,
    margin: 3,
    alignItems: 'center',
  },
  rateWrapper: {},
  txt: {
    backgroundColor: colors.greenColor,
    padding: 5,
    margin: 5,
    borderRadius: 20,
    color: 'white',
    fontSize:moderateScale(11),
  },
  labelTitle: {
    fontSize:scale(13),
    paddingBottom: 10,
    fontWeight: '500',
    color: '#333333',
    width: '100%',
    textAlign: 'center',
  },
  img: {
    width: 77,
    height: 83,
    marginStart: 10,
  },
  label: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 5,
    backgroundColor: 'white',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 0.7,
  },
  line: {
    width: '200%',
    backgroundColor: 'lightgray',
    height: 1,
    alignSelf: 'center',
  },
  wrapperTxt: {
    fontSize:moderateScale(15),
    color: '#333333',
    fontWeight: '500',
    padding: 3,
    marginStart: scale(5),
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '90%',
  },
  modalTitle: {
    fontSize:moderateScale(9),
    fontWeight: 'bold',
    marginBottom: 10,
    color: 'white',
    alignItems: 'flex-end',
    backgroundColor: colors.greenColor,
    padding: 5,
    borderRadius: 10,
  },
  modalText: {
    fontSize:moderateScale(16),
    textAlign: 'center',
    color: '#333333',
    padding: 10,
  },
  modalLine: {
    backgroundColor: '#D0D5DD',
    height: 0.6,
    width: '112%',
    padding: 1,
    marginTop: 20,
  },
  openButton: {
    paddingTop: 10,
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
  },
  confirmTxt: {
    color: colors.greenColor,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: 5,
  },
  description: {
    fontSize:moderateScale(12),
    color: '#333333',
    textAlign: 'center',
    padding: 10,
  },
});
