export const colors = {
  primary: '#3c6ce9',
  splashtext: '#fff',
  tabBarActiveTint: '#3c6ce9',
  tabBarInactiveTint: '#AAA',
  tabBarBg: '#FFFFFF',
  success: '#CDFDD4',
  medium: '#E3E3E3',
  failure: '#FDCDCD',
  placeholder: '#636363',
  strokeColor: '#D0D5DD',
  greenColor: '#66AE7B',
  openGreen: '#66ae7b',
  openOrange: '#ff9200',
  cardText: '#F5f5f5fa',
};
